### ISSUE TITLE
Error: Could not load cache adaptor file cache

### ISSUE THREAD

**Issue by humolot** [condor2/Opencart_23xx#19]
Fatal error: Uncaught Exception: Error: Could not load cache adaptor file cache! in C:\xampp\htdocs\system\library\cache.php:29 Stack trace: #0 C:\xampp\htdocs\system\framework.php(97): Cache->__construct('file', 3600) #1 C:\xampp\htdocs\system\startup.php(112): require_once('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\index.php(23): start('catalog') #3 {main} thrown in C:\xampp\htdocs\system\library\cache.php on line 29

I already moved the storage but neither the admin nor the frontend works.

**Comment by condor2** [comment]
Moved how?

No issue for me on Xampp

**Comment by humolot** [comment]
From the online environment to xampp for maintenance

**Comment by condor2** [comment]
Clear modification from storage and admin should work
