### ISSUE TITLE
After running site/install... error

### ISSUE THREAD

**Issue by batmanaround** [condor2/Opencart_23xx#20]
Fatal error: Uncaught TypeError: Argument 2 passed to Cart\Tax::setStoreAddress() must be of the type int, string given, called in .....

/var/...../system/library/cart/tax.php on line 74

**Comment by condor2** [comment]
What php version?

**Comment by batmanaround** [comment]
7.4.33

**Comment by condor2** [comment]
Test again and see if show again
https://github.com/condor2/Opencart_23xx/commit/239f6976cc962fa801f07dfdf8fcc1f51dfb6a9a
