### ISSUE TITLE
OCMOD problems

### ISSUE THREAD

**Issue by danieluramg** [condor2/Opencart_23xx#38]
Hi 
dear, I used your modification to upgrade my OC 2.3.2 with PHP 8.2 and it worked, but I can't get my OCmods to work, I don't understand what exactly I have to change in the extensions and I have several errors like in the screenshot below, is there something that can I do?
Thanks
![OCmods](https://github.com/condor2/Opencart_23xx/assets/10253175/ec869a91-0bb2-4a05-a2d1-9ef77d5ce12e)

**Comment by condor2** [comment]
Uninstall old ocmod editor and try with this and should work
[ocmod-editor.oc22-oc23.ocmod.zip](https://github.com/user-attachments/files/16008999/ocmod-editor.oc22-oc23.ocmod.zip)

**Comment by danieluramg** [comment]
Now its working fine, thanks!
