### ISSUE TITLE
Fatal error when admin change the country of store

### ISSUE THREAD

**Issue by SchrodingerAhead** [condor2/Opencart_23xx#40]
Fatal error when admin change the country of store.
Admin --> System --> Settings --> Local --> Country
![IMG_20240810_1448151](https://github.com/user-attachments/assets/ac0fb3c5-72bc-440f-a963-54c56669605b)
![IMG_20240810_1656024](https://github.com/user-attachments/assets/3e42c889-730d-4eff-b696-bc5ccad11428)

**Comment by condor2** [comment]
Sure is this latest repo?

**Comment by SchrodingerAhead** [comment]
> Sure is this latest repo?

Yes. Just downloaded the lastone. Same issue.

Xampp 7.4.33 in Windows 7 x64

**Comment by condor2** [comment]
From this repo?

Because I have tested on xampp and real hosting and work without issue.

**Comment by SchrodingerAhead** [comment]
> From this repo?
> 
> Because I have tested on xampp and real hosting and work without issue.

Yes, from this very repo. Tested on downloaded befor 2 weeks ago, and latest release 2 days ago. Maybe because xampp version ? (and php, apache, and mysql version) ?

**Comment by camrionnvmff** [comment]
uhh.I used Servbay to solve this problem, but it seems that this tool is only available on Mac

**Comment by condor2** [comment]
> > From this repo?
> > Because I have tested on xampp and real hosting and work without issue.
> 
> Yes, from this very repo. Tested on downloaded befor 2 weeks ago, and latest release 2 days ago. Maybe because xampp version ? (and php, apache, and mysql version) ?
> 

Check with latest repo. I have made some changes

**Comment by SchrodingerAhead** [comment]
> > Yes, from this very repo. Tested on downloaded befor 2 weeks ago, and latest release 2 days ago. Maybe because xampp version ? (and php, apache, and mysql version) ?
> 
> Check with latest repo. I have made some changes

Great! It works! Tested system backup and restore functions and works well.
